### ISSUE TITLE
Multi-output or coregionalization kernel

### ISSUE THREAD

**Issue by arincbulgur** [thangbui/streaming_sparse_gp#4]
Hi @thangbui, I wanted to use your algorithm for a multi-output gaussian process problem. However, I need to predict the cross-covariance between the different output dimensions and GPflow 0.4.0 doesn't allow us to define a coregion kernel with an input dimension bigger than 1. It looks like, the most recent GPflow version can handle both multi-output and coregionalization kernel. Do you have any plan to adapt the code to a recent version of GPflow? If not, would you have any suggestions to resolve the issue using the current version?

**Comment by thangbui** [comment]
Hi @arincbulgur, thanks for the interest in the code.

I do agree that it'd be great to refactor/rewrite the code to use more recent GPflow versions. We will need to compare the sparse variational code in 0.4.0 and the latest one, and make changes to the streaming classes in this repo accordingly.

This, I think, is manageable since the current repo deal with only a single output. Extending it to multi-output is a bit involved unfortunately. The good news is this [recent paper + repo](https://github.com/pmorenoz/ContinualGP) is probably exactly what you are looking for (if you are happy with using GPy).

**Comment by thangbui** [comment]
Closing this for now.
